#!/usr/bin/env bash
set -euo pipefail

export TRAIN_ALGORITHM=grpo
export GUI_OPD_ENABLE=${GUI_OPD_ENABLE:-1}
export HF_CKPT=${HF_CKPT:-path/to/evocua-8b}

export GUI_POOL_MAX_ENVS=${GUI_POOL_MAX_ENVS:-48}
export GUI_TRAJECTORY_CONCURRENCY=${GUI_TRAJECTORY_CONCURRENCY:-32}
export GUI_FAST_ROLLOUT_PROCS=${GUI_FAST_ROLLOUT_PROCS:-32}
export TARGET_IN_FLIGHT=${TARGET_IN_FLIGHT:-32}

export GUI_OPD_LOSS_MODE=${GUI_OPD_LOSS_MODE:-sampled_token}
export GUI_OPD_KL_COEF=${GUI_OPD_KL_COEF:-0.01}
export GUI_OPD_POLICY_LOSS_COEF=${GUI_OPD_POLICY_LOSS_COEF:-1.0}
export GUI_OPD_TEACHER_MAX_CONCURRENCY=${GUI_OPD_TEACHER_MAX_CONCURRENCY:-1}
export GUI_OPD_TEACHER_HTTP_MAX_RETRIES=${GUI_OPD_TEACHER_HTTP_MAX_RETRIES:-10}
export GUI_OPD_GATE_BETA=${GUI_OPD_GATE_BETA:-5.0}

export GUI_REWARD_AGENT_CLASS_PATH=${GUI_REWARD_AGENT_CLASS_PATH:-reward.analyzer_agent.AnalyzerAgent}
export ANALYZER_MODEL_PATH=${ANALYZER_MODEL_PATH:-path/to/gui-analyzer}
export ANALYZER_MODEL_NAME=${ANALYZER_MODEL_NAME:-analyzer}

export TRAIN_PRM=${TRAIN_PRM:-0}
export PRM_M=1
export PRM_TEMPERATURE=0.0
export PRM_MAX_NEW_TOKENS=${PRM_MAX_NEW_TOKENS:-4096}
export PRM_MAX_CONCURRENCY=${PRM_MAX_CONCURRENCY:-1}
export PRM_MAX_RETRIES=${PRM_MAX_RETRIES:-1}
export PRM_HTTP_MAX_RETRIES=${PRM_HTTP_MAX_RETRIES:-10}
export GUI_MAX_REWARD_IMAGE_HISTORY_LENGTH=${GUI_MAX_REWARD_IMAGE_HISTORY_LENGTH:-3}
export PRM_API_KEY_REQUIRED=0

export DYNAMIC_TRAJECTORY_ADVANTAGE_SCALING=${DYNAMIC_TRAJECTORY_ADVANTAGE_SCALING:-none}
export ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-4}
export SAVE_INTERVAL=${SAVE_INTERVAL:-10}
export NUM_ROLLOUT=${NUM_ROLLOUT:-200}

export USE_WANDB=${USE_WANDB:-0}
export USE_TENSORBOARD=${USE_TENSORBOARD:-1}
export TENSORBOARD_ROOT=${TENSORBOARD_ROOT:-path/to/tensorboard}
export TB_PROJECT_NAME=${TB_PROJECT_NAME:-slime_gui}

export RUN_TIMESTAMP=${RUN_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}
export GUI_PROJECT_NAME=${GUI_PROJECT_NAME:-slime_gui_evocua_8b_grpo-opd_async_16gpu_${RUN_TIMESTAMP}}
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
export CUSTOM_CONFIG_PATH=${CUSTOM_CONFIG_PATH:-"${SCRIPT_DIR}/gui_evocua_opd.yaml"}
export SGLANG_CONFIG=${SGLANG_CONFIG:-"${SCRIPT_DIR}/gui_grpo_opd_analyzer_sglang.yaml"}
source "${SCRIPT_DIR}/gui_evocua_8b_16gpu_async_common.sh"
