#!/usr/bin/env bash
set -euo pipefail

: "${TRAIN_ALGORITHM:?Set TRAIN_ALGORITHM=grpo or gigpo before sourcing this launcher}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
export GUI_AGENT_CLASS_PATH=${GUI_AGENT_CLASS_PATH:-agents.evocua_agent.EvoCUAAgent}
export GUI_PROMPT_STYLE=${GUI_PROMPT_STYLE:-S2}
export GUI_MAX_HISTORY_TURNS=${GUI_MAX_HISTORY_TURNS:-3}
export GUI_RESIZE_FACTOR=${GUI_RESIZE_FACTOR:-32}
export GUI_MAX_IMAGE_HISTORY_LENGTH=${GUI_MAX_IMAGE_HISTORY_LENGTH:-3}
export GUI_WAIT_AFTER_RESET=${GUI_WAIT_AFTER_RESET:-60}
export GUI_SLEEP_AFTER_EXECUTION=${GUI_SLEEP_AFTER_EXECUTION:-5.0}
export GUI_COORDINATE_TYPE=${GUI_COORDINATE_TYPE:-relative}
export HF_CKPT=${HF_CKPT:-path/to/evocua-8b}
export ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-4}
export N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-8}
export ROLLOUT_MAX_RESPONSE_LEN=${ROLLOUT_MAX_RESPONSE_LEN:-32768}
export ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-1.0}
export ROLLOUT_TOP_P=${ROLLOUT_TOP_P:-1.0}
export EVAL_TEMPERATURE=${EVAL_TEMPERATURE:-0.0}
export EVAL_TOP_P=${EVAL_TOP_P:-1.0}
export SAVE_INTERVAL=${SAVE_INTERVAL:-10}
export NUM_ROLLOUT=${NUM_ROLLOUT:-200}
export CUSTOM_CONFIG_PATH=${CUSTOM_CONFIG_PATH:-"${SCRIPT_DIR}/gui_evocua_async.yaml"}
export GUI_PROJECT_NAME=${GUI_PROJECT_NAME:-slime_gui_evocua_8b_${TRAIN_ALGORITHM}_async_16gpu}
source "${SCRIPT_DIR}/gui_qwen3vl_16gpu_async_common.sh"
